src/cdd/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from .views import set_language

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'



urlpatterns = [
    path('set-language/', 
         set_language, 
         name='set_language'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('services/', include('cdd.my_librairies.services.urls')),
    path('process_manager/', include('process_manager.urls')),
    
    path('api/', include('cdd.urls_api')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
)


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('attachments/', include('attachments.urls')),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('authentication/', include('authentication.urls')),
#     path('', include('dashboard.urls')),
#     path('api/', include('api.urls')),
# ]


if settings.DEBUG:
    from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns += [
        # YOUR PATTERNS
        path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
        # Optional UI:
        path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/funnel/urls.py
from django.urls import path

from dashboard.funnel import views

app_name = 'funnel'
urlpatterns = [
    path('', views.FunnelsView.as_view(), name='funnels'),
    path('get-funnels-view/', views.GetFunnelsView.as_view(), name='get_funnels_view'),
    path('get-funnels-fields-view/', views.GetFunnelsFieldsView.as_view(), name='get_funnels_fields_view'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardDiagnosticsCDDView.as_view(), name='diagnostics'),

    path('get-tasks-diagnostics-view', views.GetTasksDiagnosticsView.as_view(), name='get_tasks_diagnostics_view'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('facilitators/', include('dashboard.facilitators.urls')),
    path('administrative-levels/', include('dashboard.administrative_levels.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('process-manager/', include('dashboard.process_manager.urls')),
    path('reports/', include('dashboard.reports.urls')),
    path('funnels/', include('dashboard.funnel.urls')),
    path('statistics/', include('dashboard.statistics.urls')),
    path('store-apps/', include('dashboard.storeapp.urls')),
]

src/dashboard/facilitators/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from authentication.models import Facilitator
from dashboard.utils import get_administrative_level_choices, get_administrative_levels_by_level, get_choices
from no_sql_client import NoSQLClient
from .functions import get_cvds
from process_manager.models import Task, Phase, Activity


class FilterTaskForm(forms.Form):
    administrative_level = forms.ChoiceField()
    phase = forms.ChoiceField()
    activity = forms.ChoiceField()
    task = forms.ChoiceField()
    is_validated = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        facilitator_db_name = initial.get('facilitator_db_name')
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        facilitator_db = nsc.get_db(facilitator_db_name)

        facilitator_docs = facilitator_db.all_docs(include_docs=True)['rows']

        query_result_phases = [('', '')]
        query_result_activities = [('', '')]
        query_result_tasks = [('', '')]
        # query_result_administrativelevels = []
        facilitator_doc = {}
        for doc in facilitator_docs:
            doc = doc.get('doc')
            if doc.get('type') == "facilitator":
                # query_result_administrativelevels = doc.get("administrative_levels")
                facilitator_doc = doc
                break
            # elif doc.get('type') == "phase" and not self.check_name(query_result_phases, doc):
            #     query_result_phases.append(doc)
            # elif doc.get('type') == "activity" and not self.check_name(query_result_activities, doc):
            #     doc["phase_order"] = 0
            #     for phase_obj in query_result_phases:
            #         if phase_obj['_id'] == doc["phase_id"]:
            #             doc["phase_order"] = phase_obj['order']
            #             break
            #     query_result_activities.append(doc)
            # elif doc.get('type') == "task" and not self.check_name(query_result_tasks, doc):
            #     doc["phase_order"] = 0
            #     doc["activity_order"] = 0
            #     for phase_obj in query_result_phases:
            #         if phase_obj['name'] == doc["phase_name"]:
            #             doc["phase_order"] = phase_obj['order']
            #             break
            #     for activity_obj in query_result_activities:
            #         if activity_obj['name'] == doc["activity_name"]:
            #             doc["activity_order"] = activity_obj['order']
            #             break
            #     query_result_tasks.append(doc)
        
        # query_result_phases = sorted(query_result_phases, key=lambda obj: obj['order'])
        # query_result_activities = sorted(query_result_activities, key=lambda obj: (str(obj["phase_order"])+str(obj["order"])))
        # query_result_tasks = sorted(query_result_tasks, key=lambda obj: (str(obj["phase_order"])+str(obj["activity_order"])+str(obj["order"])))
        # query_result_administrativelevels = sorted(query_result_administrativelevels, key=lambda obj: obj.get('name'))
        [query_result_phases.append((o.name, o.name)) for o in Phase.objects.all().order_by("order")]
        [query_result_activities.append((o.name, o.name)) for o in Activity.objects.all().order_by("phase__order", "order")]
        [query_result_tasks.append((o.name, o.name)) for o in Task.objects.all().order_by("phase__order", "activity__order", "order")]
        cvds = sorted(get_cvds(facilitator_doc), key=lambda obj: obj.get('name'))

        # self.fields['administrative_level'].widget.choices = get_choices(
        #     query_result_administrativelevels, "id", "name")
        self.fields['administrative_level'].widget.choices = get_choices(cvds, "village_id", "name")
        # self.fields['phase'].widget.choices = get_choices(query_result_phases, "name", "name")
        # self.fields['activity'].widget.choices = get_choices(query_result_activities, "name", "name")
        # self.fields['task'].widget.choices = get_choices(query_result_tasks, "name", "name")
        self.fields['phase'].widget.choices = query_result_phases
        self.fields['activity'].widget.choices = query_result_activities
        self.fields['task'].widget.choices = query_result_tasks
        self.fields['is_validated'].widget.choices = [
            ('', ''), ('Validated', _('Validated')), ('Invalidated',  _('Invalidated')),
            ('Completed', _('Completed')), ('Pending',  _('Uncompleted')), ('Untouched',  _('Unsee'))
        ]
    
    def check_name(self, liste, obj):
        for elt in liste:
            if elt.get('name') == obj.get("name"):
                return True
        return False

class FacilitatorForm(forms.Form):
    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
        'duplicated_username': _('A facilitator with that username is already registered.'),
        'administrative_level_required': _('At least one administrative level is required.'),
    }
    name = forms.CharField()
    email = forms.EmailField(required=False)
    phone = forms.CharField(required=False)
    username = forms.CharField()
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    administrative_level = forms.ChoiceField()
    administrative_levels = forms.JSONField(label='', required=False)
    sex = forms.ChoiceField(choices=(("M.", "M."), ("Mme", "Mme")))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password)
            except ValidationError as error:
                self.add_error("password2", error)

    def clean_username(self):
        username = self.cleaned_data['username']
        if Facilitator.objects.filter(username=username).exists():
            self.add_error('username', self.error_messages["duplicated_username"])
        return username

    def clean(self):
        administrative_levels = self.cleaned_data['administrative_levels']
        if not administrative_levels:
            raise forms.ValidationError(self.error_messages['administrative_level_required'])
        return super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db('administrative_levels')
        label = get_administrative_levels_by_level(administrative_levels_db)[0]['administrative_level'].upper()
        self.fields['administrative_level'].label = label

        administrative_level_choices = get_administrative_level_choices(administrative_levels_db)
        self.fields['administrative_level'].widget.choices = administrative_level_choices
        self.fields['administrative_level'].choices = administrative_level_choices
        self.fields['administrative_level'].widget.attrs['class'] = "region"
        self.fields['administrative_levels'].widget.attrs['class'] = "hidden"




class UpdateFacilitatorForm(forms.ModelForm):
    error_messages = {
        'duplicated_username': _('A facilitator with that username is already registered.'),
        'administrative_level_required': _('At least one administrative level is required.'),
    }
    
    email = forms.EmailField(required=False)
    phone = forms.CharField(required=False)
    name = forms.CharField(required=False)
    administrative_level = forms.ChoiceField(required=False)
    administrative_levels = forms.JSONField(label='', required=False)
    sex = forms.ChoiceField(choices=(("M.", "M."), ("Mme", "Mme")))

    def clean(self):
        administrative_levels = self.cleaned_data['administrative_levels']
        if not administrative_levels:
            raise forms.ValidationError(self.error_messages['administrative_level_required'])
        return super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db('administrative_levels')
        label = get_administrative_levels_by_level(administrative_levels_db)[0]['administrative_level'].upper()
        self.fields['administrative_level'].label = label

        administrative_level_choices = get_administrative_level_choices(administrative_levels_db)
        self.fields['administrative_level'].widget.choices = administrative_level_choices
        self.fields['administrative_level'].choices = administrative_level_choices
        self.fields['administrative_level'].widget.attrs['class'] = "region"
        self.fields['administrative_levels'].widget.attrs['class'] = "hidden"


    class Meta:
        model = Facilitator
        fields = [] # specify the fields to be displayed


class FilterFacilitatorForm(forms.Form):
    region = forms.ChoiceField()
    prefecture = forms.ChoiceField()
    commune = forms.ChoiceField()

src/dashboard/forms/forms.py
from django import forms
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django.utils.translation import gettext_lazy as _


class FileForm(forms.Form):
    file = forms.FileField(label='', help_text=_('Allowed file size less than or equal to 2 MB'))

    default_error_messages = {
        'file_size': _('Select a file size less than or equal to %(max_size)s. The selected file size is %(size)s.')}

    def clean_file(self):
        max_upload_size = settings.MAX_UPLOAD_SIZE
        value = self.cleaned_data.get('file')
        if value and value.size > max_upload_size:
            raise forms.ValidationError(
                self.default_error_messages['file_size'] % {
                    'max_size': filesizeformat(max_upload_size),
                    'size': filesizeformat(value.size)})
        return value

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/reports/pages/forms.py
from django import forms
from django.utils.translation import gettext_lazy


class ReportsFacilitatorsStatusForm(forms.Form):
    
    # date_start = forms.DateTimeField(label=gettext_lazy("Start"))
    # date_end = forms.DateField(label=gettext_lazy("End"))
    facilitator = forms.ChoiceField(label=gettext_lazy("Facilitator"))


    def __init__(self, facilitators,*args, **kwargs):
        super().__init__(*args, **kwargs)

        _facilitators = [('', '')]
        [_facilitators.append((o.no_sql_db_name, o.name if o.name else o.username)) for o in facilitators.order_by("name", "username")]

        self.fields['facilitator'].widget.choices = _facilitators

src/dashboard/reports/pages/views.py
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.mixins import PageMixin
from django.utils.translation import gettext_lazy
from .forms import ReportsFacilitatorsStatusForm
from authentication.models import Facilitator
from dashboard.facilitators.forms import FilterFacilitatorForm


class ReportsFacilitatorsStatusView(PageMixin, LoginRequiredMixin, FormView):
    
    template_name = 'reports/pages/facilitators.html'
    context_object_name = 'reports'
    title = gettext_lazy('reports')
    active_level1 = 'reports'
    form_class = FilterFacilitatorForm
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]

    def render_to_response(self, context, **response_kwargs):
        """
        Return a response, using the `response_class` for this view, with a
        template rendered with the given context.
        Pass response_kwargs to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_training'] = bool(self.request.GET.get('training', '0') != '0')
        context['is_develop'] = bool(self.request.GET.get('develop', '0') != '0')
        context['form_f'] = ReportsFacilitatorsStatusForm(Facilitator.objects.filter(develop_mode=context['is_develop'], training_mode=context['is_training']))

        return context

src/dashboard/storeapp/views.py
from django.utils.translation import gettext_lazy
from django.views import generic
from django.urls import reverse_lazy

from storeapp.models import StoreProject
from dashboard.mixins import PageMixin


class StoreAppsView(PageMixin, generic.ListView):
    model = StoreProject
    queryset = StoreProject.objects.all()
    template_name = 'storeapp/apps.html'
    context_object_name = 'storeapps'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]


class StoreAppView(PageMixin, generic.DetailView):
    model = StoreProject
    template_name = 'storeapp/app.html'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:storeapp:store_apps'),
            'title': gettext_lazy('Applications')
        },
        {
            'url': '',
            'title': title
        }
    ]

src/dashboard/templates/reports/pages/facilitators.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}
{% block extracss %}
    <style>
        

    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card transparent">
                <div class="card-header">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="overlay" id="spin">
                                <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                            </div>
                            <div class="card-body">
                            
                                <div class="clearfix"></div>
                                <div class="row facilitators-filter">
                                    <div class="col-2">
                                        {% bootstrap_field form.region show_label=False %}
                                    </div>
                                    <div class="col-2">
                                        {% bootstrap_field form.prefecture show_label=False %}
                                    </div>
                                    <div class="col-2">
                                        {% bootstrap_field form.commune show_label=False %}
                                    </div>
                                    <div class="col-2">
                                        {% bootstrap_field form.canton show_label=False %}
                                    </div>
                                    <div class="col-2">
                                        {% bootstrap_field form.village show_label=False %}
                                    </div>
                                    <div class="col-2">
                                        <a class="btn fs12 text-bold-family text-primary pull-right p-0" style="margin-top: 8px;"
                                        id="clear_all_filters">
                                            {% translate "Clear all filters" %}
                                        </a>
                                    </div>
                                </div>
                                        
                                <fieldset>
                                    <legend  class="text-primary text-bold">{% translate "Select dates" %}</legend>

                                    <div class="row">
                                        <div class="col-2">
                                            <div class="form-group">
                                                <label for="id_date_start">{% translate "Start" %}</label>
                                                <input type="date" name="date_start" class="form-control" 
                                                    placeholder="{% translate 'Start' %}" required id="id_date_start" />
                                            </div>
                                        </div>

                                        <div class="col-2">
                                            <div class="form-group">
                                                <label for="id_date_end">{% translate "End" %}</label>
                                                <input type="date" name="date_end" class="form-control" 
                                                    placeholder="{% translate 'End' %}" required id="id_date_end" />
                                            </div>
                                        </div>

                                        <div class="col-5">
                                            {% bootstrap_field form_f.facilitator %}
                                        </div>

                                        <div class="col-1">
                                            <div class="form-group">
                                                <label for="id_in_details">{% translate "Details" %}</label>
                                                <input type="checkbox" name="in_details" class="form-control" 
                                                    placeholder="{% translate 'End' %}" id="id_in_details" />
                                            </div>
                                        </div>

                                        <div class="col-2">
                                            <div class="form-group">
                                                <input type="button" name="generate" class="btn btn-primary" 
                                                    style="margin-top: 25px;"
                                                    value="{% translate 'Generate the link' %}" required id="id_generate" />
                                            </div>
                                        </div>
                                    </div>

                                </fieldset>
                                

                            </div>
                        </div>
                    </div>
                </div>
               
               
            </div>




            <div class="card">
                <div class="card-body table-responsive">
                    <div id="pdf-display">
                        {% comment %} <iframe src="{{ attach.attachment.uri|imgAWSS3Filter }}" width="250" height="300"></iframe> {% endcomment %}
                    </div>
                </div>
                <div class="overlay" id="spin-pdf">
                    <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>


        </div>

    </div>

<input type="hidden" name="type_field" id="id_type_field" value="" />

{% endblock %}





{% block javascript %}
    {{ block.super }}


    <script src="{% static 'js/cascade_requests.js' %}"></script>
    <script type="text/javascript">
        let ids = ["id_region", "id_prefecture", "id_commune", "id_canton", "id_village"]
        var type_field = "";
        let spin = $('#spin');
        let administrative_level = $('#id_administrative_level');
        let id_region = $('#id_region');
        let id_prefecture = $('#id_prefecture');
        let id_commune = $('#id_commune');
        let id_canton = $('#id_canton');
        let id_village = $('#id_village');
        let spin_pdf = $('#spin-pdf');



        function loadFacilitators(type_field="") {
            if($("#id_"+type_field).val() || type_field == "all"){  
                spin.show();
                $(".facilitators-filter select").attr('disabled', true);
                $.ajax({
                    type: 'GET',
                    url: "{% url 'dashboard:administrative_levels:get_choices_for_next_administrative_level_all' %}",
                    data: {
                        parent_id: $("#id_"+type_field).val()
                    },
                    success: function (data) {
                        if(type_field == "region"){
                            set_datas_administrative_level(id_prefecture, data.prefectures);
                            set_datas_administrative_level(id_commune, data.communes);
                            set_datas_administrative_level(id_canton, data.cantons);
                            set_datas_administrative_level(id_village, data.villages);
                        }else if(type_field == "prefecture"){
                            set_datas_administrative_level(id_commune, data.communes);
                            set_datas_administrative_level(id_canton, data.cantons);
                            set_datas_administrative_level(id_village, data.villages);
                        }else if(type_field == "commune"){
                            set_datas_administrative_level(id_canton, data.cantons);
                            set_datas_administrative_level(id_village, data.villages);
                        }else if(type_field == "canton"){
                            set_datas_administrative_level(id_village, data.villages);
                        }
                        
                    },
                    error: function (data) {
                        spin.hide();
                        alert(error_server_message + "Error " + data.status);
                        $(".facilitators-filter select").attr('disabled', false);
                    }
                }).done(function () {
                        spin.hide();
                        $(".facilitators-filter select").attr('disabled', false);
                    }
                );

            }
            




            
        }

        loadFacilitators("all");


        $('.facilitators-filter select').on('change', function () {
            type_field = "";
            if($(this).attr('id') && $(this).val()){
                type_field = $(this).attr('id').split('_')[1];
                $('#id_type_field').val(type_field);
            }
            loadFacilitators(type_field);
            $('#pdf-display').html(``);
        });

        $("#clear_all_filters").on("click", function () {
            $('.facilitators-filter input').val('');
            $('.facilitators-filter select').val(null).trigger('change.select2');
            loadFacilitators("all");
        });


        $('fieldset select').on('change', function () {
            $('#pdf-display').html(``);
        });
        $('fieldset input').on('change', function () {
            $('#pdf-display').html(``);
        });


        $("#id_generate").click(function(event){
            event.preventDefault();
            let val_date_start = $("#id_date_start").val();
            let val_date_end = $("#id_date_end").val();
            let val_facilitator = $("#id_facilitator").val();

            if(val_date_end && val_date_start){
                spin_pdf.show();
                let href = "";
                if(val_facilitator){
                    //href = `{% url 'dashboard:reports:pdf:app_pdf_facilitator_status' '_var_' %}`;
                    href = `{% url 'dashboard:reports:excel_csv:app_excel_csv_facilitator_status' '_var_' %}`;
                    href = href.replace('_var_', val_facilitator);
                }else{
                    //href = `{% url 'dashboard:reports:pdf:app_pdf_facilitators_status' %}`;
                    href = `{% url 'dashboard:reports:excel_csv:app_excel_csv_facilitators_status' %}`;
                }
                
                href += (`?id_region=` + id_region.val() +
                `&id_prefecture=` + id_prefecture.val() + `&id_commune=` + id_commune.val() + `&id_canton=` + id_canton.val() + 
                `&id_village=` + id_village.val() + `&type_field=` + $('#id_type_field').val() + 
                `&is_training=` + "{{ is_training }}" + `&is_develop=` + "{{ is_develop }}" + 
                `&id_in_details=`+ (id_in_details.checked ? 1 : 0) + 
                `&val_date_start=` + val_date_start + `&val_date_end=` + val_date_end);
                
                
                {% comment %} $('#pdf-display').html(`
                <a target="_blank" href=`+ href +`>{% translate 'Link generated. Click to generate the PDF' %}</a>
                `); {% endcomment %}
                $('#pdf-display').html(`
                <a target="_blank" href=`+ href +`>{% translate 'Link generated. Click to generate the EXCEL' %}</a>
                `);
                
                spin_pdf.hide();
                {% comment %} $.ajax({
                    type: "GET",
                    //url: "{% url 'dashboard:reports:pdf:app_pdf_facilitators_status' %}",
                    url: "{% url 'dashboard:reports:pdf:app_excel_csv_facilitators_status' %}",
                    data: {
                        id_region: id_region.val(),
                        id_prefecture: id_prefecture.val(),
                        id_commune: id_commune.val(),
                        id_canton: id_canton.val(),
                        id_village: id_village.val(),
                        type_field: type_field,
                        is_training: "{{ is_training }}",
                        is_develop: "{{ is_develop }}",
                        download: 1
                    },
                    success: function (response) {
                        spin_pdf.hide();
                        $('#pdf-display').html(response);
                    },
                    error: function (data) {
                        spin_pdf.hide();
                        alert(error_server_message + "Error " + data.status);
                    }
                }); {% endcomment %}
            }else{
                alert("{% translate 'You have to fill all the fields' %}");
            }
        });
        spin_pdf.hide();
    </script>
    


{% endblock %}

{% block select2 %}
    <script type="text/javascript">
        $("#id_region").select2({
            placeholder: "{% translate 'Region' %}",
            allowClear: true
        });
        $("#id_prefecture").select2({
            placeholder: "{% translate 'Prefecture' %}",
            allowClear: true,
        });
        $("#id_commune").select2({
            placeholder: "{% translate 'Commune' %}",
            allowClear: true,
        });
         $("#id_canton").select2({
            placeholder: "{% translate 'Canton' %}",
            allowClear: true,
        });
         $("#id_village").select2({
            placeholder: "{% translate 'Village' %}",
            allowClear: true,
        });

         $("#id_facilitator").select2({
            placeholder: "{% translate 'Facilitator' %}",
            allowClear: true,
        });

        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');
            
    </script>
{% endblock select2 %}