src/cdd/my_librairies/services/urls.py
from django.urls import path
from . import views_file

app_name = 'services'

urlpatterns = [
    path('get-excel-sheets-names', views_file.get_excel_sheets_names, name='get_excel_sheets_names'),
]

src/cdd/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from .views import set_language

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'



urlpatterns = [
    path('set-language/', 
         set_language, 
         name='set_language'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('services/', include('cdd.my_librairies.services.urls')),
    path('process_manager/', include('process_manager.urls')),
    
    path('api/', include('cdd.urls_api')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
)


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('attachments/', include('attachments.urls')),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('authentication/', include('authentication.urls')),
#     path('', include('dashboard.urls')),
#     path('api/', include('api.urls')),
# ]


if settings.DEBUG:
    from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns += [
        # YOUR PATTERNS
        path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
        # Optional UI:
        path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/funnel/urls.py
from django.urls import path

from dashboard.funnel import views

app_name = 'funnel'
urlpatterns = [
    path('', views.FunnelsView.as_view(), name='funnels'),
    path('get-funnels-view/', views.GetFunnelsView.as_view(), name='get_funnels_view'),
    path('get-funnels-fields-view/', views.GetFunnelsFieldsView.as_view(), name='get_funnels_fields_view'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardDiagnosticsCDDView.as_view(), name='diagnostics'),

    path('get-tasks-diagnostics-view', views.GetTasksDiagnosticsView.as_view(), name='get_tasks_diagnostics_view'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('facilitators/', include('dashboard.facilitators.urls')),
    path('administrative-levels/', include('dashboard.administrative_levels.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('process-manager/', include('dashboard.process_manager.urls')),
    path('reports/', include('dashboard.reports.urls')),
    path('funnels/', include('dashboard.funnel.urls')),
    path('statistics/', include('dashboard.statistics.urls')),
    path('store-apps/', include('dashboard.storeapp.urls')),
]

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/administrative_levels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from dashboard.mixins import AJAXRequestMixin, JSONResponseMixin
from dashboard.utils import get_child_administrative_levels, get_parent_administrative_level
from no_sql_client import NoSQLClient
from administrativelevels import models as administrativelevels_models
from .functions import get_administrative_levels_under_json, get_cascade_administrative_levels_by_administrative_level_id

class GetChoicesForNextAdministrativeLevelView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        parent_id = request.GET.get('parent_id')
        exclude_lower_level = request.GET.get('exclude_lower_level', None)
        project_id = request.GET.get('project_id', 1)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db("administrative_levels")
        data = get_child_administrative_levels(administrative_levels_db, parent_id, project_id)

        if data and exclude_lower_level and not get_child_administrative_levels(
                administrative_levels_db, data[0]['administrative_id']):
            data = []

        return self.render_to_json_response(data, safe=False)


class GetAncestorAdministrativeLevelsView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        administrative_id = request.GET.get('administrative_id', None)
        ancestors = []
        if administrative_id:
            nsc = NoSQLClient()
            administrative_levels_db = nsc.get_db("administrative_levels")
            has_parent = True
            while has_parent:
                parent = get_parent_administrative_level(administrative_levels_db, administrative_id)
                if parent:
                    administrative_id = parent['administrative_id']
                    ancestors.insert(0, administrative_id)
                else:
                    has_parent = False

        return self.render_to_json_response(ancestors, safe=False)


class GetChoicesForNextAdministrativeLevelAllView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        # parent_id = request.GET.get('parent_id')

        # nsc = NoSQLClient()
        # administrative_levels_db = nsc.get_db("administrative_levels")
        # data = get_child_administrative_levels(administrative_levels_db, parent_id)

        # parent_name = None
        # ad = data[0] if data else None
        # if ad:
        #     if ad.get('administrative_level') == 'Prefecture':
        #         parent_name = "region"
        #     elif ad.get('administrative_level') == 'Commune':
        #         parent_name = "prefecture"
        #     elif ad.get('administrative_level') == 'Canton':
        #         parent_name = "commune"
        #     elif ad.get('administrative_level') == 'Village':
        #         parent_name = "canton"

        # # if parent_name == "region":
        # datas = {
        #     "prefectures": data if parent_name == "region" else [], 
        #     "communes": data if parent_name == "prefecture" else [], 
        #     "cantons": data if parent_name == "commune" else [], 
        #     "villages": data if parent_name == "canton" else []
        # }
        # for p in datas["prefectures"]:
        #     [datas["communes"].append(o) for o in get_child_administrative_levels(administrative_levels_db, p.get("administrative_id"))]

        # for c in datas["communes"]:
        #     [datas["cantons"].append(o) for o in get_child_administrative_levels(administrative_levels_db, c.get("administrative_id"))]
        
        # for c in datas["cantons"]:
        #     [datas["villages"].append(o) for o in get_child_administrative_levels(administrative_levels_db, c.get("administrative_id"))]


        # datas = {}

        # _id = request.GET.get('parent_id')
        # if _id:
        #     ad_obj = administrativelevels_models.AdministrativeLevel.objects.using('mis').get(id=int(_id))

        #     ads = ad_obj.administrativelevel_set.get_queryset()
        #     _type = ad_obj.type
        #     datas = {
        #         "prefectures": ads if _type == "Region" else [], 
        #         "communes": ads if _type == "Prefecture" else [], 
        #         "cantons": ads if _type == "Commune" else [], 
        #         "villages": ads if _type == "Canton" else []
        #     }
        #     for p in datas["prefectures"]:
        #         [datas["communes"].append(o) for o in p.administrativelevel_set.get_queryset()]

        #     for c in datas["communes"]:
        #         [datas["cantons"].append(o) for o in c.administrativelevel_set.get_queryset()]
            
        #     for c in datas["cantons"]:
        #         [datas["villages"].append(o) for o in c.administrativelevel_set.get_queryset()]

        #     datas["prefectures"] = get_administrative_levels_under_json(datas["prefectures"])
        #     datas["communes"] = get_administrative_levels_under_json(datas["communes"])
        #     datas["cantons"] = get_administrative_levels_under_json(datas["cantons"])
        #     datas["villages"] = get_administrative_levels_under_json(datas["villages"])

        #     return self.render_to_json_response(datas, safe=False)
    
        # return self.render_to_json_response(datas, safe=False)

        return self.render_to_json_response(
            get_cascade_administrative_levels_by_administrative_level_id(request.GET.get('parent_id')), 
            safe=False
        )

src/dashboard/authentication/views.py
from django.shortcuts import render, redirect
from rest_framework import status
from django.utils.translation import gettext_lazy
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.mixins import PageMixin
from authentication.permissions import AdminPermissionRequiredMixin
from dashboard.authentication.forms import CreateUserForm, UpdateUserForm
from django.contrib.auth.models import User, Group, Permission
from django.forms.models import model_to_dict
from django.contrib import messages
from django.http import Http404


def handler400(request, exception):
    return render(
        request,
        template_name='common/400.html',
        status=status.HTTP_400_BAD_REQUEST,
        content_type='text/html'
    )


def handler403(request, exception):
    return render(
        request,
        template_name='common/403.html',
        status=status.HTTP_403_FORBIDDEN,
        content_type='text/html'
    )


def handler404(request, exception):
    return render(
        request,
        template_name='common/404.html',
        status=status.HTTP_404_NOT_FOUND,
        content_type='text/html'
    )


def handler500(request):
    return render(
        request,
        template_name='common/500.html',
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content_type='text/html'
    )




class UsersListView(PageMixin, LoginRequiredMixin, generic.ListView):
    """Display user list"""

    model = User
    template_name = 'authentication/users.html'
    context_object_name = 'users'
    title = gettext_lazy('Users')
    active_level1 = 'users'
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]

    


class CreateUpdateUserFormView(PageMixin, LoginRequiredMixin, AdminPermissionRequiredMixin, generic.FormView):
    template_name = 'authentication/create.html'
    title = gettext_lazy('Create User')
    active_level1 = 'users'
    form_class = CreateUserForm
    success_url = reverse_lazy('dashboard:authentication:users')
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:authentication:users'),
            'title': gettext_lazy('Users')
        },
        {
            'url': '',
            'title': title
        }
    ]
    id = 0
    def dispatch(self, request, *args, **kwargs):
        try:
            self.id = kwargs['id']
        except Exception:
            pass
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        ctx = super(CreateUpdateUserFormView, self).get_context_data(**kwargs)
        if self.id:
            form = UpdateUserForm(instance=User.objects.get(id=self.id))
            ctx['form'] = form

            ctx['title'] = gettext_lazy('Update User')
            ctx['breadcrumb'] = [
                {
                    'url': reverse_lazy('dashboard:authentication:users'),
                    'title': gettext_lazy('Users')
                },
                {
                    'url': '',
                    'title': ctx['title']
                }
            ]

        return ctx

    def post(self, request, *args, **kwargs):
        if self.id:
            form = UpdateUserForm(request.POST, instance=User.objects.get(id=self.id))
        else:
            form = CreateUserForm(request.POST)
        if form.is_valid():
            
            groups = form.cleaned_data['groups']
            user_permissions = form.cleaned_data['user_permissions']
            try:
                for g in groups:
                    Group.objects.using('mis').get(name=g.name)
                for u_p in user_permissions:
                    Permission.objects.using('mis').get(name=u_p.name)
            except Exception as exc:
                messages.info(request, gettext_lazy(exc.__str__()))
                return super(CreateUpdateUserFormView, self).get(request, *args, **kwargs)

            instance = form.save()

            # Save on MIS DB
            a_dict = model_to_dict(instance)
            
            del a_dict['id']
            del a_dict['groups']
            del a_dict['user_permissions']
            user = None
            if self.id:
                try:
                    _user = User.objects.get(id=self.id)
                    # user_id = User.objects.using('mis').get(username=_user.username).id
                    # a_dict['id'] = user_id
                    # User.objects.using('mis').update(**a_dict)
                    user = User.objects.using('mis').get(username=_user.username)
                    for k, v in a_dict.items():
                        setattr(user, k, v)
                except Exception as exc:
                    messages.info(request, gettext_lazy(exc.__str__()))
                    return redirect('dashboard:authentication:users')
            else:
                User.objects.using('mis').create(**a_dict)
                user = User.objects.using('mis').get(username=instance.username)
            print(groups, user_permissions)
            instance.groups.set([])
            user.groups.set([])
            instance.user_permissions.set([])
            user.user_permissions.set([])
            for g in groups:
                instance.groups.add(g)
                user.groups.add(Group.objects.using('mis').get(name=g.name))
            for u_p in user_permissions:
                instance.user_permissions.add(u_p)
                user.user_permissions.add(Permission.objects.using('mis').get(name=u_p.name))
                
            instance.save()
            user.save(using='mis')
            #End

            return redirect('dashboard:authentication:users')
        return super(CreateUpdateUserFormView, self).get(request, *args, **kwargs)


class DeleteUserFormView(PageMixin, LoginRequiredMixin, AdminPermissionRequiredMixin, generic.TemplateView):
    template_name = 'authentication/delete.html'
    title = gettext_lazy('Delete User')
    active_level1 = 'users'
    success_url = reverse_lazy('dashboard:authentication:users')
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:authentication:users'),
            'title': gettext_lazy('Users')
        },
        {
            'url': '',
            'title': title
        }
    ]

    id = 0
    def dispatch(self, request, *args, **kwargs):
        try:
            self.id = kwargs['id']
        except Exception:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(DeleteUserFormView, self).get_context_data(**kwargs)
        try:
            if self.id:
                ctx['object'] = User.objects.get(id=self.id)
            return ctx
        except Exception as exc:
            messages.info(self.request, gettext_lazy(exc.__str__()))
            return redirect('dashboard:authentication:users')

    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=self.id)
            user.delete()
            return redirect('dashboard:authentication:users')
        except Exception as exc:
            messages.info(request, gettext_lazy(exc.__str__()))
        
        return super(DeleteUserFormView, self).get(request, *args, **kwargs)

src/dashboard/storeapp/views.py
from django.utils.translation import gettext_lazy
from django.views import generic
from django.urls import reverse_lazy

from storeapp.models import StoreProject
from dashboard.mixins import PageMixin


class StoreAppsView(PageMixin, generic.ListView):
    model = StoreProject
    queryset = StoreProject.objects.all()
    template_name = 'storeapp/apps.html'
    context_object_name = 'storeapps'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]


class StoreAppView(PageMixin, generic.DetailView):
    model = StoreProject
    template_name = 'storeapp/app.html'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:storeapp:store_apps'),
            'title': gettext_lazy('Applications')
        },
        {
            'url': '',
            'title': title
        }
    ]

src/dashboard/templates/components/modal_upload_one_sheet.html
{% load i18n %}

<!-- Button modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#upload-csv-file">
    <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i> {% translate 'Load file' %}
</button>

<!-- Modal -->
<div class="modal fade" id="upload-csv-file" tabindex="-1" role="dialog"
    aria-labelledby="UploadTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <form method="post" enctype="multipart/form-data"
                action="{% url upload_url %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">
                        {% translate 'Upload CSV file' %}
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <input type="hidden" name="_type" value="{{ type_object }}" />
                    
                    <div class="form-group" id="sheet_name_content">
                        <label for="sheet_name">{% translate 'Sheet Name' %}</label>
                        <select class="form-control" id="sheet_name" name="sheet_name" style="width: 100%;">
                        </select>
                    </div>

                    <div class="file-field big">
                        <a class="btn-floating btn-lg amber darken-2 mt-0 float-left">
                            <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                            <input type="file" name="file" required id="file" 
                            accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                        </a>
                    </div>
                    <br/><br/>
                    


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" 
                        style="display: inline-block !important;" onclick="window.location.reload();"><i class="fa fa-refresh"></i></button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                        style="display: inline-block !important;">{% translate 'Close' %}</button>
                    <button type="submit" class="btn btn-primary" style="display: inline-block !important;" id="submit_btn_upload">
                        {% translate 'Upload' %}
                    </button>
                </div>

            </form>
        </div>

    </div>
</div>
<!-- End Modal -->

<script>
    var sheet_name_content = document.getElementById("sheet_name_content")
    sheet_name_content.style.display = "none";
    var file = document.getElementById("file");
    file.onchange = function(event){
        if(this.files.length != 0){   
            datafile = this.files[0];
            var data =  new FormData();
            data.append("file", datafile);
            data.append("csrfmiddlewaretoken", "{{ csrf_token }}");

            fetch("{% url 'services:get_excel_sheets_names' %}", {
                method: 'POST',
                /*headers: {
                'Content-Type': 'multipart/form-data'
                },*/
                body: data
            }).then(
                response => response.json() 
            ).then(datas => {
                sheet_name_content.style.display = "block";
                var sheet_name = document.getElementById("sheet_name");
                sheet_name.innerHTML = "";
                names = datas["names"];
                if(names){
                    for(var i=0; i < names.length; i++){
                        sheet_name.innerHTML += `<option value="${names[i]}">${names[i]}</option>`;
                    }
                }
            }
            ).catch(
                error => console.log(error)
            );

        }
    }

    {% comment %} setInterval(function() {
        if(document.getElementById('submit_btn_upload').disabled == true){
            document.getElementById('submit_btn_upload').disabled = false;
        }
    }, 15 * 1000); {% endcomment %}
</script>