src/cdd/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from .views import set_language

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'



urlpatterns = [
    path('set-language/', 
         set_language, 
         name='set_language'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('services/', include('cdd.my_librairies.services.urls')),
    path('process_manager/', include('process_manager.urls')),
    
    path('api/', include('cdd.urls_api')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
)


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('attachments/', include('attachments.urls')),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('authentication/', include('authentication.urls')),
#     path('', include('dashboard.urls')),
#     path('api/', include('api.urls')),
# ]


if settings.DEBUG:
    from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns += [
        # YOUR PATTERNS
        path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
        # Optional UI:
        path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/funnel/urls.py
from django.urls import path

from dashboard.funnel import views

app_name = 'funnel'
urlpatterns = [
    path('', views.FunnelsView.as_view(), name='funnels'),
    path('get-funnels-view/', views.GetFunnelsView.as_view(), name='get_funnels_view'),
    path('get-funnels-fields-view/', views.GetFunnelsFieldsView.as_view(), name='get_funnels_fields_view'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardDiagnosticsCDDView.as_view(), name='diagnostics'),

    path('get-tasks-diagnostics-view', views.GetTasksDiagnosticsView.as_view(), name='get_tasks_diagnostics_view'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('facilitators/', include('dashboard.facilitators.urls')),
    path('administrative-levels/', include('dashboard.administrative_levels.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('process-manager/', include('dashboard.process_manager.urls')),
    path('reports/', include('dashboard.reports.urls')),
    path('funnels/', include('dashboard.funnel.urls')),
    path('statistics/', include('dashboard.statistics.urls')),
    path('store-apps/', include('dashboard.storeapp.urls')),
]

src/dashboard/diagnostics/forms.py
from django import forms
from django.utils.translation import gettext_lazy

from authentication.models import Facilitator
from dashboard.utils import get_administrative_levels_by_type, get_documents_by_type, get_choices
from no_sql_client import NoSQLClient
from dashboard.facilitators.functions import get_cvds
from process_manager.models import Task, Phase, Activity
from administrativelevels.models import AdministrativeLevel


class DiagnosticsForm(forms.Form):
    
    phase = forms.ChoiceField(label=gettext_lazy("Phase"))
    activity = forms.ChoiceField(label=gettext_lazy("Activity"))
    task = forms.ChoiceField(label=gettext_lazy("Task"))

    region = forms.ChoiceField(label=gettext_lazy("Region"))
    prefecture = forms.ChoiceField(label=gettext_lazy("Prefecture"))
    commune = forms.ChoiceField(label=gettext_lazy("Commune"))
    canton = forms.ChoiceField(label=gettext_lazy("Canton"))
    village = forms.ChoiceField(label=gettext_lazy("Village"))


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # nsc = NoSQLClient()
        # administrative_levels_db = nsc.get_db('administrative_levels')
        # process_design = nsc.get_db('process_design')

        query_result_phases = [('', '')]
        query_result_activities = [('', '')]
        query_result_tasks = [('', '')]

        query_result_regions = [('', '')]
        query_result_prefectures = [('', '')]
        query_result_communes = [('', '')]
        query_result_cantons = [('', '')]
        query_result_villages = [('', '')]


        [query_result_phases.append((o.id, o.name)) for o in Phase.objects.all().order_by("order")]
        [query_result_activities.append((o.id, o.name)) for o in Activity.objects.all().order_by("phase__order", "order")]
        [query_result_tasks.append((o.id, o.name)) for o in Task.objects.all().order_by("phase__order", "activity__order", "order")]

        [query_result_regions.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Region").order_by("name")]
        [query_result_prefectures.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Prefecture").order_by("name")]
        [query_result_communes.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Commune").order_by("name")]
        [query_result_cantons.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Canton").order_by("name")]
        [query_result_villages.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Village").order_by("name")]
        # for label in ["phase", "activity", "task"]:
        #     try:
        #         elements = get_choices(get_documents_by_type(process_design, label), 'sql_id', "name", True)
        #         self.fields[label].widget.choices = elements
        #         self.fields[label].choices = elements
        #         self.fields[label].widget.attrs['class'] = label
        #     except Exception as exc:
        #         pass
        self.fields['phase'].widget.choices = query_result_phases
        self.fields['activity'].widget.choices = query_result_activities
        self.fields['task'].widget.choices = query_result_tasks

        # for label in ["region", "prefecture", "commune", "canton", "village"]:
        #     try:
        #         administrative_level_choices = get_choices(
        #             get_administrative_levels_by_type(administrative_levels_db, label.title()), 
        #             'administrative_id', "name", True)
        #         self.fields[label].widget.choices = administrative_level_choices
        #         self.fields[label].choices = administrative_level_choices
        #         self.fields[label].widget.attrs['class'] = label
        #     except Exception as exc:
        #         pass
        self.fields['region'].widget.choices = query_result_regions
        self.fields['prefecture'].widget.choices = query_result_prefectures
        self.fields['commune'].widget.choices = query_result_communes
        self.fields['canton'].widget.choices = query_result_cantons
        self.fields['village'].widget.choices = query_result_villages
        

src/dashboard/facilitators/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from authentication.models import Facilitator
from dashboard.utils import get_administrative_level_choices, get_administrative_levels_by_level, get_choices
from no_sql_client import NoSQLClient
from .functions import get_cvds
from process_manager.models import Task, Phase, Activity


class FilterTaskForm(forms.Form):
    administrative_level = forms.ChoiceField()
    phase = forms.ChoiceField()
    activity = forms.ChoiceField()
    task = forms.ChoiceField()
    is_validated = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        facilitator_db_name = initial.get('facilitator_db_name')
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        facilitator_db = nsc.get_db(facilitator_db_name)

        facilitator_docs = facilitator_db.all_docs(include_docs=True)['rows']

        query_result_phases = [('', '')]
        query_result_activities = [('', '')]
        query_result_tasks = [('', '')]
        # query_result_administrativelevels = []
        facilitator_doc = {}
        for doc in facilitator_docs:
            doc = doc.get('doc')
            if doc.get('type') == "facilitator":
                # query_result_administrativelevels = doc.get("administrative_levels")
                facilitator_doc = doc
                break
            # elif doc.get('type') == "phase" and not self.check_name(query_result_phases, doc):
            #     query_result_phases.append(doc)
            # elif doc.get('type') == "activity" and not self.check_name(query_result_activities, doc):
            #     doc["phase_order"] = 0
            #     for phase_obj in query_result_phases:
            #         if phase_obj['_id'] == doc["phase_id"]:
            #             doc["phase_order"] = phase_obj['order']
            #             break
            #     query_result_activities.append(doc)
            # elif doc.get('type') == "task" and not self.check_name(query_result_tasks, doc):
            #     doc["phase_order"] = 0
            #     doc["activity_order"] = 0
            #     for phase_obj in query_result_phases:
            #         if phase_obj['name'] == doc["phase_name"]:
            #             doc["phase_order"] = phase_obj['order']
            #             break
            #     for activity_obj in query_result_activities:
            #         if activity_obj['name'] == doc["activity_name"]:
            #             doc["activity_order"] = activity_obj['order']
            #             break
            #     query_result_tasks.append(doc)
        
        # query_result_phases = sorted(query_result_phases, key=lambda obj: obj['order'])
        # query_result_activities = sorted(query_result_activities, key=lambda obj: (str(obj["phase_order"])+str(obj["order"])))
        # query_result_tasks = sorted(query_result_tasks, key=lambda obj: (str(obj["phase_order"])+str(obj["activity_order"])+str(obj["order"])))
        # query_result_administrativelevels = sorted(query_result_administrativelevels, key=lambda obj: obj.get('name'))
        [query_result_phases.append((o.name, o.name)) for o in Phase.objects.all().order_by("order")]
        [query_result_activities.append((o.name, o.name)) for o in Activity.objects.all().order_by("phase__order", "order")]
        [query_result_tasks.append((o.name, o.name)) for o in Task.objects.all().order_by("phase__order", "activity__order", "order")]
        cvds = sorted(get_cvds(facilitator_doc), key=lambda obj: obj.get('name'))

        # self.fields['administrative_level'].widget.choices = get_choices(
        #     query_result_administrativelevels, "id", "name")
        self.fields['administrative_level'].widget.choices = get_choices(cvds, "village_id", "name")
        # self.fields['phase'].widget.choices = get_choices(query_result_phases, "name", "name")
        # self.fields['activity'].widget.choices = get_choices(query_result_activities, "name", "name")
        # self.fields['task'].widget.choices = get_choices(query_result_tasks, "name", "name")
        self.fields['phase'].widget.choices = query_result_phases
        self.fields['activity'].widget.choices = query_result_activities
        self.fields['task'].widget.choices = query_result_tasks
        self.fields['is_validated'].widget.choices = [
            ('', ''), ('Validated', _('Validated')), ('Invalidated',  _('Invalidated')),
            ('Completed', _('Completed')), ('Pending',  _('Uncompleted')), ('Untouched',  _('Unsee'))
        ]
    
    def check_name(self, liste, obj):
        for elt in liste:
            if elt.get('name') == obj.get("name"):
                return True
        return False

class FacilitatorForm(forms.Form):
    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
        'duplicated_username': _('A facilitator with that username is already registered.'),
        'administrative_level_required': _('At least one administrative level is required.'),
    }
    name = forms.CharField()
    email = forms.EmailField(required=False)
    phone = forms.CharField(required=False)
    username = forms.CharField()
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    administrative_level = forms.ChoiceField()
    administrative_levels = forms.JSONField(label='', required=False)
    sex = forms.ChoiceField(choices=(("M.", "M."), ("Mme", "Mme")))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password)
            except ValidationError as error:
                self.add_error("password2", error)

    def clean_username(self):
        username = self.cleaned_data['username']
        if Facilitator.objects.filter(username=username).exists():
            self.add_error('username', self.error_messages["duplicated_username"])
        return username

    def clean(self):
        administrative_levels = self.cleaned_data['administrative_levels']
        if not administrative_levels:
            raise forms.ValidationError(self.error_messages['administrative_level_required'])
        return super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db('administrative_levels')
        label = get_administrative_levels_by_level(administrative_levels_db)[0]['administrative_level'].upper()
        self.fields['administrative_level'].label = label

        administrative_level_choices = get_administrative_level_choices(administrative_levels_db)
        self.fields['administrative_level'].widget.choices = administrative_level_choices
        self.fields['administrative_level'].choices = administrative_level_choices
        self.fields['administrative_level'].widget.attrs['class'] = "region"
        self.fields['administrative_levels'].widget.attrs['class'] = "hidden"




class UpdateFacilitatorForm(forms.ModelForm):
    error_messages = {
        'duplicated_username': _('A facilitator with that username is already registered.'),
        'administrative_level_required': _('At least one administrative level is required.'),
    }
    
    email = forms.EmailField(required=False)
    phone = forms.CharField(required=False)
    name = forms.CharField(required=False)
    administrative_level = forms.ChoiceField(required=False)
    administrative_levels = forms.JSONField(label='', required=False)
    sex = forms.ChoiceField(choices=(("M.", "M."), ("Mme", "Mme")))

    def clean(self):
        administrative_levels = self.cleaned_data['administrative_levels']
        if not administrative_levels:
            raise forms.ValidationError(self.error_messages['administrative_level_required'])
        return super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db('administrative_levels')
        label = get_administrative_levels_by_level(administrative_levels_db)[0]['administrative_level'].upper()
        self.fields['administrative_level'].label = label

        administrative_level_choices = get_administrative_level_choices(administrative_levels_db)
        self.fields['administrative_level'].widget.choices = administrative_level_choices
        self.fields['administrative_level'].choices = administrative_level_choices
        self.fields['administrative_level'].widget.attrs['class'] = "region"
        self.fields['administrative_levels'].widget.attrs['class'] = "hidden"


    class Meta:
        model = Facilitator
        fields = [] # specify the fields to be displayed


class FilterFacilitatorForm(forms.Form):
    region = forms.ChoiceField()
    prefecture = forms.ChoiceField()
    commune = forms.ChoiceField()

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/templates/facilitators/create.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                &times;
                            </button>
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="card">
                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                {% bootstrap_field form.name %}
                                {% bootstrap_field form.email %}
                                {% bootstrap_field form.phone %}
                                {% bootstrap_field form.sex %}
                            </div>
                            <div class="col-6">
                                {% bootstrap_field form.username %}
                                {% bootstrap_field form.password1 %}
                                {% bootstrap_field form.password2 %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label>{% trans "Add administrative levels" %}</label>
                                {% bootstrap_field form.administrative_level layout='horizontal' %}
                                <div class="float-right">
                                    <a id="add" class="btn btn-primary btn-sm rounded-xl disabled">
                                        {% translate "ADD" %}
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div id="selected_regions" class="col-12"></div>
                        </div>
                        {% bootstrap_field form.administrative_levels %}
                    </div>
                    <div class="card-footer">
                        <button id="submit" type="submit" class="btn btn-primary btn-sm rounded-xl" disabled>
                            {% translate "SAVE" %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}


{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        let get_ancestors_url = '{% url 'dashboard:administrative_levels:get_ancestor_administrative_levels' %}';
        let get_choices_url = '{% url 'dashboard:administrative_levels:get_choices_for_next_administrative_level' %}';
        let choice_placeholder = "{% translate 'Click to select location' %}";
        changeRegionTrigger(get_choices_url, choice_placeholder);
        loadRegionSelectors(get_ancestors_url);
    </script>
{% endblock javascript %}

{% block select2 %}
    <script src="{% static 'js/dynamicRegionSelector.js' %}"></script>
    <script type="text/javascript">
        $("#id_administrative_level").select2({
            placeholder: "{% translate 'Click to select location' %}",
            allowClear: true
        });
        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');

    </script>
{% endblock select2 %}

src/dashboard/templates/facilitators/facilitator_percent_completed.html
<b
    style="color:
    {% if percentage_tasks_completed < 10 %}red
    {% elif percentage_tasks_completed < 30 %}orange
    {% elif percentage_tasks_completed < 50 %}purple
    {% elif percentage_tasks_completed < 70 %}black
    {% elif percentage_tasks_completed < 90 %}#04e1e1
    {% elif percentage_tasks_completed < 100 %}blue
    {% else %}green
    {% endif %};
    "
>
    {% if percentage_tasks_completed < 10 %}
        0{{ percentage_tasks_completed|floatformat:"2" }}
    {% else %}
        {{ percentage_tasks_completed|floatformat:"2" }}
    {% endif %}%
</b>

src/dashboard/templates/facilitators/update.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                &times;
                            </button>
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-8">
                            {% translate 'Facilitator not assigned' as not_assigned %}
                            <div class="profile-header">
                                <span {% if not facilitator_doc %}class="text-warning"{% endif %} id="name">
                                    {{ facilitator_doc.name|default:not_assigned }}
                                </span>
                            </div>
                            <p class="mt-2 lh14 text-gray-light">
                                {% translate 'Tel' %}: <span id="phone">{{ facilitator_doc.phone }}</span>
                                <br>
                                {% translate 'Email' %}: <span id="email">{{ facilitator_doc.email }}</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                {% bootstrap_field form.name %}
                                {% bootstrap_field form.email %}
                            </div>
                            <div class="col-6">
                                {% bootstrap_field form.phone %}
                                {% bootstrap_field form.sex %}
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-12">
                                <label>{% trans "Add administrative levels" %}</label>
                                {% bootstrap_field form.administrative_level layout='horizontal' %}
                                <div class="float-right">
                                    <a id="add" class="btn btn-primary btn-sm rounded-xl disabled">
                                        {% translate "ADD" %}
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div id="selected_regions" class="col-12">
                                {% for elt in facilitator_administrative_levels %}
                                    <a class='tag mt-2' >
                                        <i value='{{ elt.id }}' class='fa fa-remove mr-2 link remove-region' title='Remove'></i>
                                        {{ elt.name }} {% if elt.cvd_name and elt.cvd_name != elt.name %}(CVD : {{ elt.cvd_name }}){% endif %}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                        {% bootstrap_field form.administrative_levels %}
                    </div>
                    <div class="card-footer">
                        <button  type="submit" class="btn btn-primary btn-sm rounded-xl" data-toggle="modal" data-target="#static-modal">
                            {% translate "SAVE" %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block modals %}
    <div id="static-modal" class="modal" role="dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog modal-confirmation">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title mx-auto">
                        <div class="fs29 text-bold-family text-primary">
                            
                        </div>
                    </div>
                </div>
                
                <div class="modal-body">
                    <div class="overlay-wrapper">
                        <div class="card">
                            <div class="card-body table-responsive">
                                {% translate "synchronization in progress..." %}
                            </div>
                            <div class="overlay" id="spin">
                                <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                            </div>
                        </div>
                    </div>
                </div>
                    
            </div>
        </div>
    </div>
{% endblock %}





{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        let _selected_region_json = {};
        {% for elt in facilitator_administrative_levels %}
            _selected_region_json = {
                "name": "{{ elt.name }}",
                "id": "{{ elt.id }}"
            }; 
            selected_regions_json.push(_selected_region_json);
        {% endfor %}
        $("#id_administrative_levels").val(JSON.stringify(selected_regions_json));
        
        $("#id_phone").val("{{ facilitator_doc.phone }}");
        $("#id_email").val("{{ facilitator_doc.email }}");
        $("#id_name").val("{{ facilitator_doc.name }}");
        $("#id_sex").val("{{ facilitator_doc.sex }}");
    </script>

    <script type="text/javascript">
        let get_ancestors_url = '{% url 'dashboard:administrative_levels:get_ancestor_administrative_levels' %}';
        let get_choices_url = '{% url 'dashboard:administrative_levels:get_choices_for_next_administrative_level' %}';
        let choice_placeholder = "{% translate 'Click to select location' %}";
        changeRegionTrigger(get_choices_url, choice_placeholder);
        loadRegionSelectors(get_ancestors_url);
    </script>
{% endblock javascript %}

{% block select2 %}
    <script src="{% static 'js/dynamicRegionSelector.js' %}"></script>
    <script type="text/javascript">
        $("#id_administrative_level").select2({
            placeholder: "{% translate 'Click to select location' %}",
            allowClear: true
        });
        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');

    </script>
{% endblock select2 %}

src/dashboard/templates/facilitators/validation_invalidation.html
{% load static i18n custom_tags %}

<div style="width: 30%; margin: auto; float: left;" >
    <button type="button" name="invalidate_valide" 
        class="btn {% if task.validated %}btn-warning action_code_0{% else %}btn-primary action_code_1{% endif %} invalidate_valide" 
        required id="id_invalidate_valide_{{ task|get:'_id' }}">
        {% if task.validated %}
            {% translate 'Mark as invalidated' %}
        {% else %}
            {% translate 'Mark as validated' %}
        {% endif %}
    </button>
</div>

{% if task.validated == True or task.validated == False %}
{% else %}
    <div style="width: 30%; margin: auto; float: left;" id="id_invalidate_{{ task|get:'_id' }}" >
        <button type="button" name="invalidate_valide" id="_id_invalidate_{{ task|get:'_id' }}" 
            class="btn btn-warning  action_code_0 invalidate_valide" 
            required>
                {% translate 'Mark as invalidated' %}
        </button>
    </div>
{% endif %}