src/cdd/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from .views import set_language

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'



urlpatterns = [
    path('set-language/', 
         set_language, 
         name='set_language'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('services/', include('cdd.my_librairies.services.urls')),
    path('process_manager/', include('process_manager.urls')),
    
    path('api/', include('cdd.urls_api')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
)


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('attachments/', include('attachments.urls')),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('authentication/', include('authentication.urls')),
#     path('', include('dashboard.urls')),
#     path('api/', include('api.urls')),
# ]


if settings.DEBUG:
    from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns += [
        # YOUR PATTERNS
        path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
        # Optional UI:
        path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/funnel/urls.py
from django.urls import path

from dashboard.funnel import views

app_name = 'funnel'
urlpatterns = [
    path('', views.FunnelsView.as_view(), name='funnels'),
    path('get-funnels-view/', views.GetFunnelsView.as_view(), name='get_funnels_view'),
    path('get-funnels-fields-view/', views.GetFunnelsFieldsView.as_view(), name='get_funnels_fields_view'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardDiagnosticsCDDView.as_view(), name='diagnostics'),

    path('get-tasks-diagnostics-view', views.GetTasksDiagnosticsView.as_view(), name='get_tasks_diagnostics_view'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('facilitators/', include('dashboard.facilitators.urls')),
    path('administrative-levels/', include('dashboard.administrative_levels.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('process-manager/', include('dashboard.process_manager.urls')),
    path('reports/', include('dashboard.reports.urls')),
    path('funnels/', include('dashboard.funnel.urls')),
    path('statistics/', include('dashboard.statistics.urls')),
    path('store-apps/', include('dashboard.storeapp.urls')),
]

src/dashboard/authentication/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext as _
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class EmailAuthenticationForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = _('Email')

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = User.objects.filter(email__iexact=email).first()

        if not user:
            raise self.get_invalid_login_error()
        if email and password:
            self.user_cache = authenticate(self.request, username=user.username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class CreateUserForm(UserCreationForm):
                
    class Meta:
        """docstring for Meta"""
        model = User
        fields = (
            'username', 'password1', 'password2', 'last_name', 'first_name', 'email', 
            'is_superuser', 'is_staff', 'is_active', 'groups', 'user_permissions'
        )

class UpdateUserForm(forms.ModelForm):
                
    class Meta:
        """docstring for Meta"""
        model = User
        fields = (
            'username', 'last_name', 'first_name', 'email', 
            'is_superuser', 'is_staff', 'is_active', 'groups', 'user_permissions'
        )

        

src/dashboard/diagnostics/forms.py
from django import forms
from django.utils.translation import gettext_lazy

from authentication.models import Facilitator
from dashboard.utils import get_administrative_levels_by_type, get_documents_by_type, get_choices
from no_sql_client import NoSQLClient
from dashboard.facilitators.functions import get_cvds
from process_manager.models import Task, Phase, Activity
from administrativelevels.models import AdministrativeLevel


class DiagnosticsForm(forms.Form):
    
    phase = forms.ChoiceField(label=gettext_lazy("Phase"))
    activity = forms.ChoiceField(label=gettext_lazy("Activity"))
    task = forms.ChoiceField(label=gettext_lazy("Task"))

    region = forms.ChoiceField(label=gettext_lazy("Region"))
    prefecture = forms.ChoiceField(label=gettext_lazy("Prefecture"))
    commune = forms.ChoiceField(label=gettext_lazy("Commune"))
    canton = forms.ChoiceField(label=gettext_lazy("Canton"))
    village = forms.ChoiceField(label=gettext_lazy("Village"))


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # nsc = NoSQLClient()
        # administrative_levels_db = nsc.get_db('administrative_levels')
        # process_design = nsc.get_db('process_design')

        query_result_phases = [('', '')]
        query_result_activities = [('', '')]
        query_result_tasks = [('', '')]

        query_result_regions = [('', '')]
        query_result_prefectures = [('', '')]
        query_result_communes = [('', '')]
        query_result_cantons = [('', '')]
        query_result_villages = [('', '')]


        [query_result_phases.append((o.id, o.name)) for o in Phase.objects.all().order_by("order")]
        [query_result_activities.append((o.id, o.name)) for o in Activity.objects.all().order_by("phase__order", "order")]
        [query_result_tasks.append((o.id, o.name)) for o in Task.objects.all().order_by("phase__order", "activity__order", "order")]

        [query_result_regions.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Region").order_by("name")]
        [query_result_prefectures.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Prefecture").order_by("name")]
        [query_result_communes.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Commune").order_by("name")]
        [query_result_cantons.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Canton").order_by("name")]
        [query_result_villages.append((o.id, o.name)) for o in AdministrativeLevel.objects.using('mis').filter(type="Village").order_by("name")]
        # for label in ["phase", "activity", "task"]:
        #     try:
        #         elements = get_choices(get_documents_by_type(process_design, label), 'sql_id', "name", True)
        #         self.fields[label].widget.choices = elements
        #         self.fields[label].choices = elements
        #         self.fields[label].widget.attrs['class'] = label
        #     except Exception as exc:
        #         pass
        self.fields['phase'].widget.choices = query_result_phases
        self.fields['activity'].widget.choices = query_result_activities
        self.fields['task'].widget.choices = query_result_tasks

        # for label in ["region", "prefecture", "commune", "canton", "village"]:
        #     try:
        #         administrative_level_choices = get_choices(
        #             get_administrative_levels_by_type(administrative_levels_db, label.title()), 
        #             'administrative_id', "name", True)
        #         self.fields[label].widget.choices = administrative_level_choices
        #         self.fields[label].choices = administrative_level_choices
        #         self.fields[label].widget.attrs['class'] = label
        #     except Exception as exc:
        #         pass
        self.fields['region'].widget.choices = query_result_regions
        self.fields['prefecture'].widget.choices = query_result_prefectures
        self.fields['commune'].widget.choices = query_result_communes
        self.fields['canton'].widget.choices = query_result_cantons
        self.fields['village'].widget.choices = query_result_villages
        

src/dashboard/administrative_levels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from dashboard.mixins import AJAXRequestMixin, JSONResponseMixin
from dashboard.utils import get_child_administrative_levels, get_parent_administrative_level
from no_sql_client import NoSQLClient
from administrativelevels import models as administrativelevels_models
from .functions import get_administrative_levels_under_json, get_cascade_administrative_levels_by_administrative_level_id

class GetChoicesForNextAdministrativeLevelView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        parent_id = request.GET.get('parent_id')
        exclude_lower_level = request.GET.get('exclude_lower_level', None)
        project_id = request.GET.get('project_id', 1)

        nsc = NoSQLClient()
        administrative_levels_db = nsc.get_db("administrative_levels")
        data = get_child_administrative_levels(administrative_levels_db, parent_id, project_id)

        if data and exclude_lower_level and not get_child_administrative_levels(
                administrative_levels_db, data[0]['administrative_id']):
            data = []

        return self.render_to_json_response(data, safe=False)


class GetAncestorAdministrativeLevelsView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        administrative_id = request.GET.get('administrative_id', None)
        ancestors = []
        if administrative_id:
            nsc = NoSQLClient()
            administrative_levels_db = nsc.get_db("administrative_levels")
            has_parent = True
            while has_parent:
                parent = get_parent_administrative_level(administrative_levels_db, administrative_id)
                if parent:
                    administrative_id = parent['administrative_id']
                    ancestors.insert(0, administrative_id)
                else:
                    has_parent = False

        return self.render_to_json_response(ancestors, safe=False)


class GetChoicesForNextAdministrativeLevelAllView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        # parent_id = request.GET.get('parent_id')

        # nsc = NoSQLClient()
        # administrative_levels_db = nsc.get_db("administrative_levels")
        # data = get_child_administrative_levels(administrative_levels_db, parent_id)

        # parent_name = None
        # ad = data[0] if data else None
        # if ad:
        #     if ad.get('administrative_level') == 'Prefecture':
        #         parent_name = "region"
        #     elif ad.get('administrative_level') == 'Commune':
        #         parent_name = "prefecture"
        #     elif ad.get('administrative_level') == 'Canton':
        #         parent_name = "commune"
        #     elif ad.get('administrative_level') == 'Village':
        #         parent_name = "canton"

        # # if parent_name == "region":
        # datas = {
        #     "prefectures": data if parent_name == "region" else [], 
        #     "communes": data if parent_name == "prefecture" else [], 
        #     "cantons": data if parent_name == "commune" else [], 
        #     "villages": data if parent_name == "canton" else []
        # }
        # for p in datas["prefectures"]:
        #     [datas["communes"].append(o) for o in get_child_administrative_levels(administrative_levels_db, p.get("administrative_id"))]

        # for c in datas["communes"]:
        #     [datas["cantons"].append(o) for o in get_child_administrative_levels(administrative_levels_db, c.get("administrative_id"))]
        
        # for c in datas["cantons"]:
        #     [datas["villages"].append(o) for o in get_child_administrative_levels(administrative_levels_db, c.get("administrative_id"))]


        # datas = {}

        # _id = request.GET.get('parent_id')
        # if _id:
        #     ad_obj = administrativelevels_models.AdministrativeLevel.objects.using('mis').get(id=int(_id))

        #     ads = ad_obj.administrativelevel_set.get_queryset()
        #     _type = ad_obj.type
        #     datas = {
        #         "prefectures": ads if _type == "Region" else [], 
        #         "communes": ads if _type == "Prefecture" else [], 
        #         "cantons": ads if _type == "Commune" else [], 
        #         "villages": ads if _type == "Canton" else []
        #     }
        #     for p in datas["prefectures"]:
        #         [datas["communes"].append(o) for o in p.administrativelevel_set.get_queryset()]

        #     for c in datas["communes"]:
        #         [datas["cantons"].append(o) for o in c.administrativelevel_set.get_queryset()]
            
        #     for c in datas["cantons"]:
        #         [datas["villages"].append(o) for o in c.administrativelevel_set.get_queryset()]

        #     datas["prefectures"] = get_administrative_levels_under_json(datas["prefectures"])
        #     datas["communes"] = get_administrative_levels_under_json(datas["communes"])
        #     datas["cantons"] = get_administrative_levels_under_json(datas["cantons"])
        #     datas["villages"] = get_administrative_levels_under_json(datas["villages"])

        #     return self.render_to_json_response(datas, safe=False)
    
        # return self.render_to_json_response(datas, safe=False)

        return self.render_to_json_response(
            get_cascade_administrative_levels_by_administrative_level_id(request.GET.get('parent_id')), 
            safe=False
        )

src/dashboard/reports/pages/views.py
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.mixins import PageMixin
from django.utils.translation import gettext_lazy
from .forms import ReportsFacilitatorsStatusForm
from authentication.models import Facilitator
from dashboard.facilitators.forms import FilterFacilitatorForm


class ReportsFacilitatorsStatusView(PageMixin, LoginRequiredMixin, FormView):
    
    template_name = 'reports/pages/facilitators.html'
    context_object_name = 'reports'
    title = gettext_lazy('reports')
    active_level1 = 'reports'
    form_class = FilterFacilitatorForm
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]

    def render_to_response(self, context, **response_kwargs):
        """
        Return a response, using the `response_class` for this view, with a
        template rendered with the given context.
        Pass response_kwargs to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_training'] = bool(self.request.GET.get('training', '0') != '0')
        context['is_develop'] = bool(self.request.GET.get('develop', '0') != '0')
        context['form_f'] = ReportsFacilitatorsStatusForm(Facilitator.objects.filter(develop_mode=context['is_develop'], training_mode=context['is_training']))

        return context

src/dashboard/storeapp/views.py
from django.utils.translation import gettext_lazy
from django.views import generic
from django.urls import reverse_lazy

from storeapp.models import StoreProject
from dashboard.mixins import PageMixin


class StoreAppsView(PageMixin, generic.ListView):
    model = StoreProject
    queryset = StoreProject.objects.all()
    template_name = 'storeapp/apps.html'
    context_object_name = 'storeapps'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]


class StoreAppView(PageMixin, generic.DetailView):
    model = StoreProject
    template_name = 'storeapp/app.html'
    title = gettext_lazy('Applications')
    active_level1 = 'storeapp'
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:storeapp:store_apps'),
            'title': gettext_lazy('Applications')
        },
        {
            'url': '',
            'title': title
        }
    ]

src/dashboard/templates/funnel/filters.html
{% load bootstrap4 static i18n %}
<div class="row">
    <div class="col-12">
        <h2 class="text-primary text-bold">{% translate "Filter by" %}</h2>
    </div>
    {% for field in form %}
        {% if forloop.counter <= 3 %}
        <div class="col-4">
            {% bootstrap_field field %}
        </div>
        {% else %}
        <div class="col-2">
            {% bootstrap_field field %}
        </div>
        {% endif %}
    {% endfor %}

</div>

<script type="text/javascript">
    
    $("#id_phase").select2({
        placeholder: "{% translate 'Phase' %}",
        allowClear: true,
    });
    $("#id_activity").select2({
        placeholder: "{% translate 'Activity' %}",
        allowClear: true,
    });
    $("#id_task").select2({
        placeholder: "{% translate 'Task' %}",
        allowClear: true,
    });
    $("#id_region").select2({
        placeholder: "{% translate 'Region' %}",
        allowClear: true
    });
    $("#id_prefecture").select2({
        placeholder: "{% translate 'Prefecture' %}",
        allowClear: true,
    });
    $("#id_commune").select2({
        placeholder: "{% translate 'Commune' %}",
        allowClear: true,
    });
    $("#id_canton").select2({
        placeholder: "{% translate 'Canton' %}",
        allowClear: true
    });
    $("#id_village").select2({
        placeholder: "{% translate 'Village' %}",
        allowClear: true
    });
    
    $('.select2-selection__arrow').append(
        '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');
    
</script>

src/dashboard/templates/funnel/funnel_list copy.html
{% load static i18n custom_tags %}

{% for key, value in funnels.data.items %}
<div class="card">
    <div class="card-body" >
        <div class="row">
            <div class="col-12">
                <h6><b>{{ forloop.counter }}</b> &nbsp; &nbsp; {{ key }}</h6>
                {% for k, v in value.items %}
                    {% if v.id %}
                        <div class="row">
                            <div class="col-2">
                                <p>{{ k }}</p>
                            </div>
                            <div class="col-8">
                                <div class="progress">
                                    {% with percent=v|get:"percentage_tasks_completed" %}
                                    <div class="progress-bar" role="progressbar" style='width: {{ percent|replace_comma_by_dot }}%' 
                                        aria-valuenow='{{ percent }}|replace_comma_by_dot' aria-valuemin="0" aria-valuemax="100"></div>
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="col-1">
                                <p>{{ v|get:"nbr_tasks_completed" }}/{{ v|get:"nbr_tasks" }}</p>
                            </div>
                            <div class="col-1">
                                <p>{% with percent=v|get:"percentage_tasks_completed" %}{{ percent|get_to_percent_str }}{% endwith %}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="row">
                    <div class="col-10">
                        <b style="float: right;">{% translate 'Total' %}</b>
                    </div>
                    <div class="col-1">
                        <p>{{ value|get:"nbr_tasks_completed" }}/{{ value|get:"nbr_tasks" }}</p>
                    </div>
                    <div class="col-1">
                        <p>{% with percent=value|get:"percentage_tasks_completed" %}{{ percent|get_to_percent_str }}{% endwith %}</p>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
{% endfor %}

src/dashboard/templates/funnel/funnel_list.html
{% load static i18n custom_tags %}

{% for key, value in funnels.data.items %}
<div class="card">
    <div class="card-body" >
        <div class="row">
            <div class="col-12">
                <h6><b>{{ forloop.counter }}</b> &nbsp; &nbsp; {{ key }}</h6>
                {% for k, v in value.items %}
                    {% if v.id %}
                        <div class="row">
                            <div class="col-2">
                                <p>{{ k }}</p>
                            </div>
                            <div class="col-8">
                                <div class="progress">
                                    {% with percent=v|get:"percentage_tasks_completed" %}
                                    <div class="progress-bar" role="progressbar" style='width: {{ percent|replace_comma_by_dot }}%' 
                                        aria-valuenow='{{ percent }}|replace_comma_by_dot' aria-valuemin="0" aria-valuemax="100"></div>
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="col-1">
                                <p>{{ v|get:"nbr_tasks_completed" }}/{{ v|get:"nbr_tasks" }}</p>
                            </div>
                            <div class="col-1">
                                <p>{% with percent=v|get:"percentage_tasks_completed" %}{{ percent|get_to_percent_str }}{% endwith %}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="row">
                    <div class="col-10">
                        <b style="float: right;">{% translate 'Total' %}</b>
                    </div>
                    <div class="col-1">
                        <p>{{ value|get:"nbr_tasks_completed" }}/{{ value|get:"nbr_tasks" }}</p>
                    </div>
                    <div class="col-1">
                        <p>{% with percent=value|get:"percentage_tasks_completed" %}{{ percent|get_to_percent_str }}{% endwith %}</p>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
{% endfor %}

src/dashboard/templates/funnel/funnels copy.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}
{% block extracss %}

{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card transparent">
                <div class="card-header">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <h2 class="text-primary text-bold">{% translate "Filter by" %}</h2>
                                    </div>
                                    {% for field in form %}
                                        {% if forloop.counter <= 3 %}
                                        <div class="col-4">
                                            {% bootstrap_field field %}
                                        </div>
                                        {% else %}
                                        <div class="col-2">
                                            {% bootstrap_field field %}
                                        </div>
                                        {% endif %}
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="overlay-wrapper">
                        <div class="row">
                        
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body" id="funnels" >

                                        

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="overlay z-index1000" id="spin">
                            <i class="fas fa-10x fa-sync-alt fa-spin">
                            </i>
                        </div>
                        

                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'plugins/mapbox-gl-js/v2.6.1/mapbox-gl.js' %}"></script>
    <script>
    
    </script>


{% endblock %}
{% block select2 %}
    <script src="{% static 'js/dynamicRegionSelector.js' %}"></script>
    <script type="text/javascript">
        let spin = $('#spin');
        spin.hide();

        let funnels = $("#funnels");
        {% for field in list_fields %}
            $(document).on("change", ("#id_"+"{{ field }}"), function (event) {
                
                if(this.value){
                    spin.show();

                    $.ajax({
                        type: 'GET',
                        url: `{% url 'dashboard:funnel:get_funnels_view' %}`,
                        data: {
                            type: "{{ field }}",
                            sql_id: this.value
                        },
                        success: function (data) {
                            funnels.html(data);
                            spin.hide();
                        },
                        error: function (data) {
                            alert(error_server_message + "Error " + data.status);
                            spin.hide();
                        }
                    });
                }else{
                    funnels.html('');
                }
                
            });


        {% endfor %}








        
        $("#id_phase").select2({
            placeholder: "{% translate 'Phase' %}",
            allowClear: true,
        });
        $("#id_activity").select2({
            placeholder: "{% translate 'Activity' %}",
            allowClear: true,
        });
        $("#id_task").select2({
            placeholder: "{% translate 'Task' %}",
            allowClear: true,
        });
        $("#id_region").select2({
            placeholder: "{% translate 'Region' %}",
            allowClear: true
        });
        $("#id_prefecture").select2({
            placeholder: "{% translate 'Prefecture' %}",
            allowClear: true,
        });
        $("#id_commune").select2({
            placeholder: "{% translate 'Commune' %}",
            allowClear: true,
        });
        $("#id_canton").select2({
            placeholder: "{% translate 'Canton' %}",
            allowClear: true
        });
        $("#id_village").select2({
            placeholder: "{% translate 'Village' %}",
            allowClear: true
        });
        
        {% comment %} $('b[role="presentation"]').hide(); {% endcomment %}
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');
        

        $.ajax({
            type: 'GET',
            url: `{% url 'dashboard:funnel:get_funnels_view' %}`,
            data: {
                type: null,
                sql_id: null
            },
            success: function (data) {
                funnels.html(data);
                spin.hide();
            },
            error: function (data) {
                alert(error_server_message + "Error " + data.status);
                spin.hide();
            }
        });


    </script>
{% endblock select2 %}